# Generated by Django 5.1.4 on 2024-12-18 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0008_customuser_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connection',
            name='deleted_at',
        ),
    ]
