# Generated by Django 5.1.4 on 2024-12-18 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0009_remove_connection_deleted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='followers',
        ),
        migrations.AddField(
            model_name='customuser',
            name='followers_count',
            field=models.IntegerField(default=0),
        ),
    ]
