# Generated by Django 5.1.4 on 2024-12-19 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0013_remove_notification_title_customuser_followers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user',
        ),
    ]
