# Generated by Django 5.1.4 on 2024-12-19 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0014_remove_customuser_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='followers_count',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_bio',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_profile_image',
            field=models.ImageField(default='default_profile.png', upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='photo',
            field=models.ImageField(blank=True, default='default_photo.jpg', null=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='text',
            field=models.CharField(max_length=280),
        ),
        migrations.DeleteModel(
            name='Connection',
        ),
    ]
