# Generated by Django 5.1.4 on 2024-12-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0017_notification_notification_type_notification_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like', 'Like'), ('follow', 'Follow'), ('message', 'Message'), ('tweet', 'Tweet'), ('comment', 'Comment')], default='message', max_length=10),
        ),
    ]
